/*
 * Client-side site search.
 *
 * Webflow's search is a hosted feature - the /search route is rendered by
 * Webflow's servers. A static export keeps the search form but ships no results
 * markup and has no backend behind it, so every search came back blank. This
 * reads a prebuilt index instead and renders the results in the browser.
 *
 * Wiring (re-add these two lines after a Webflow re-export, which overwrites
 * search.html):
 *   <link href="css/site-search.css" rel="stylesheet" type="text/css">  in <head>
 *   <script src="js/site-search.js" type="text/javascript"></script>    before </body>
 *
 * The index is generated by tools/build-search-index.js - re-run it whenever
 * page content changes, or results go stale.
 */

(function () {
  'use strict';

  // Resolve everything against the script's own URL rather than the page's, so
  // this keeps working if a search box is ever added to a nested page.
  var script = document.currentScript || document.querySelector('script[src*="site-search.js"]');
  var BASE = script ? script.src.replace(/js\/site-search\.js(\?.*)?$/, '') : '';
  var INDEX_URL = BASE + 'search-index.json';

  var MAX_RESULTS = 25;
  var SNIPPET_CHARS = 200;
  var SNIPPET_LEAD = 70;

  // Most pages share a "Create a digital menu free… orders and payments" CTA, so
  // broad queries technically match almost the whole site. Once a result set is
  // long enough to have a real tail, drop what scores far below the best match.
  var TAIL_MIN_RESULTS = 8;
  var TAIL_SCORE_RATIO = 0.1;

  // Relative weights per field. Body text is the baseline; a title hit is worth
  // far more than a passing mention halfway down a page.
  var FIELDS = [
    { key: 'title', weight: 14 },
    { key: 'slug', weight: 6 },
    { key: 'headings', weight: 6 },
    { key: 'description', weight: 4 },
    { key: 'text', weight: 1 },
  ];

  // Function words carry no signal but match nearly every page, so a query like
  // "accept payments from customers" would otherwise return the whole site.
  var STOPWORDS = {};
  ('a an and are as at be but by for from has have how i if in is it its of on or'
    + ' our so than that the their then there these they this to was we what when'
    + ' where which who why will with you your')
    .split(' ')
    .forEach(function (word) { STOPWORDS[word] = true; });

  var form = document.querySelector('form.search-form, form[action="/search"], form[action="/search.html"]');
  if (!form) return;

  var input = form.querySelector('input[name="query"]') || form.querySelector('input[type="search"]');
  if (!input) return;

  // Only the search page renders results. Elsewhere the form is left alone and
  // submits normally, which navigates here.
  if (!/(^|\/)search(\.html)?$/i.test(location.pathname.replace(/\/+$/, ''))) return;

  var pageTitle = document.title;
  var indexPromise = null;
  var results = buildResultsRegion();

  render(currentQuery());

  form.addEventListener('submit', function (event) {
    var query = input.value.trim();
    if (!query || !window.history || !window.history.pushState) return; // fall back to a normal GET
    event.preventDefault();
    history.pushState({ query: query }, '', location.pathname + '?query=' + encodeURIComponent(query));
    render(query);
  });

  window.addEventListener('popstate', function () {
    var query = currentQuery();
    input.value = query;
    render(query);
  });

  function currentQuery() {
    // Webflow's form posts the term as ?query=; ?q= is accepted as a courtesy
    // for hand-typed and externally linked URLs.
    var params = new URLSearchParams(location.search);
    return (params.get('query') || params.get('q') || '').trim();
  }

  function buildResultsRegion() {
    var region = document.createElement('div');
    region.className = 'site-search-results';
    region.id = 'site-search-results';
    region.setAttribute('aria-live', 'polite');

    var status = document.createElement('p');
    status.className = 'site-search-status';
    region.appendChild(status);

    var list = document.createElement('ol');
    list.className = 'site-search-list';
    region.appendChild(list);

    // Inside the form's own grid cell, so it inherits the column span Webflow
    // assigned rather than being auto-placed somewhere unrelated in the grid.
    (form.parentNode || document.body).appendChild(region);

    input.setAttribute('aria-controls', region.id);
    return { region: region, status: status, list: list };
  }

  function render(query) {
    input.value = query;
    document.title = query ? 'Search: ' + query + ' · ' + pageTitle : pageTitle;
    results.list.textContent = '';

    if (!query) {
      setStatus('Enter a term above to search the site.');
      return;
    }

    setStatus('Searching…');
    loadIndex().then(
      function (pages) {
        var terms = tokenize(query);
        if (!terms.length) {
          setStatus('Enter a term above to search the site.');
          return;
        }
        show(query, terms, search(pages, terms));
      },
      function (error) {
        // eslint-disable-next-line no-console
        console.error('site-search: could not load ' + INDEX_URL, error);
        setStatus('Search is temporarily unavailable. Please try again later.');
      }
    );
  }

  function show(query, terms, matches) {
    results.list.textContent = '';

    if (!matches.length) {
      setStatus('No results for ', query, '. Try a different or more general term.');
      return;
    }

    var shown = matches.slice(0, MAX_RESULTS);
    var count = matches.length === 1 ? '1 result for ' : matches.length + ' results for ';
    setStatus(count, query, matches.length > shown.length ? '. Showing the first ' + shown.length + '.' : '');

    var highlighter = highlightPattern(terms);
    shown.forEach(function (match) {
      results.list.appendChild(resultItem(match, highlighter));
    });
  }

  function resultItem(match, highlighter) {
    var page = match.page;

    var item = document.createElement('li');
    item.className = 'site-search-item';

    var link = document.createElement('a');
    link.className = 'site-search-link';
    link.href = BASE + page.url.replace(/^\//, '');

    var title = document.createElement('span');
    title.className = 'site-search-title';
    highlightInto(title, page.title, highlighter);
    link.appendChild(title);

    var url = document.createElement('span');
    url.className = 'site-search-url';
    url.textContent = prettyUrl(page.url);
    link.appendChild(url);

    var snippetText = snippet(page, match.terms);
    if (snippetText) {
      var snip = document.createElement('span');
      snip.className = 'site-search-snippet';
      highlightInto(snip, snippetText, highlighter);
      link.appendChild(snip);
    }

    item.appendChild(link);
    return item;
  }

  function setStatus() {
    // Arguments alternate plain text and, for odd positions, user-supplied text
    // that is inserted as a text node so a query can never inject markup.
    results.status.textContent = '';
    for (var i = 0; i < arguments.length; i++) {
      var value = arguments[i];
      if (!value) continue;
      if (i % 2 === 1) {
        var strong = document.createElement('strong');
        strong.textContent = '“' + value + '”';
        results.status.appendChild(strong);
      } else {
        results.status.appendChild(document.createTextNode(value));
      }
    }
  }

  function loadIndex() {
    if (indexPromise) return indexPromise;
    indexPromise = fetch(INDEX_URL, { credentials: 'same-origin' })
      .then(function (response) {
        if (!response.ok) throw new Error('HTTP ' + response.status);
        return response.json();
      })
      .then(function (data) {
        var pages = (data && data.pages) || [];
        pages.forEach(prepare);
        return pages;
      })
      .catch(function (error) {
        indexPromise = null; // let a later search retry
        throw error;
      });
    return indexPromise;
  }

  // Precompute the normalised, space-padded haystacks once per page load;
  // matching then reduces to indexOf.
  function prepare(page) {
    page.headingsText = (page.headings || []).join(' ');
    page.fields = {
      title: pad(page.title),
      slug: pad(page.url.replace(/\.html$/, '').replace(/[/-]/g, ' ')),
      headings: pad(page.headingsText),
      description: pad(page.description),
      text: pad(page.text),
    };
  }

  function pad(value) {
    return ' ' + normalize(value || '') + ' ';
  }

  function normalize(value) {
    return value
      .toLowerCase()
      .replace(/['‘’ʼ]/g, '') // customer's -> customers
      .replace(/[^a-z0-9]+/g, ' ')
      .trim();
  }

  function tokenize(query) {
    var all = normalize(query).split(' ').filter(Boolean);
    // De-duplicate so "menu menu" does not double-score, and cap the term count
    // so a pasted paragraph cannot turn into a pathological scan.
    var unique = all.filter(function (term, i) { return all.indexOf(term) === i; }).slice(0, 10);

    // Single characters and stray digits match far too much to be useful.
    var significant = unique.filter(function (term) {
      return term.length > 1 && !STOPWORDS[term];
    });

    // A query that is nothing but stopwords ("who are we") still deserves an answer.
    return significant.length ? significant : unique;
  }

  // How much each term narrows things down. A word on every page says nothing
  // about which page you want; a rare one is the whole reason for the search.
  function inverseDocumentFrequency(pages, terms) {
    var idf = {};
    terms.forEach(function (term) {
      var documents = 0;
      pages.forEach(function (page) {
        for (var i = 0; i < FIELDS.length; i++) {
          if (page.fields[FIELDS[i].key].indexOf(' ' + term) !== -1) {
            documents++;
            return;
          }
        }
      });
      // Always positive, so a match never scores zero however common the term.
      idf[term] = Math.log(1 + pages.length / (1 + documents));
    });
    return idf;
  }

  function search(pages, terms) {
    var phrase = terms.length > 1 ? ' ' + terms.join(' ') : null;
    var idf = inverseDocumentFrequency(pages, terms);
    // Longer queries are descriptive rather than exact, so require a majority of
    // the terms instead of letting one incidental word qualify a page.
    var minMatched = terms.length > 2 ? Math.ceil(terms.length / 2) : 1;

    var matches = pages
      .map(function (page) {
        var score = 0;
        var matched = 0;

        terms.forEach(function (term) {
          var hit = false;
          FIELDS.forEach(function (field) {
            var haystack = page.fields[field.key];
            if (!haystack) return;
            // Matching at a word start means "restaur" finds "restaurants".
            var count = occurrences(haystack, ' ' + term);
            if (!count) return;
            hit = true;
            score += field.weight * Math.min(count, 3) * idf[term];
            // Exact whole-word hits outrank partial ones.
            if (haystack.indexOf(' ' + term + ' ') !== -1) score += field.weight * 0.5 * idf[term];
          });
          if (hit) matched++;
        });

        if (phrase) {
          FIELDS.forEach(function (field) {
            if (page.fields[field.key] && page.fields[field.key].indexOf(phrase) !== -1) {
              score += field.weight * 4;
            }
          });
        }

        return { page: page, score: score, matched: matched, terms: terms };
      })
      .filter(function (match) { return match.matched >= minMatched; })
      .sort(function (a, b) {
        // Pages matching every term always beat pages matching only some.
        if (b.matched !== a.matched) return b.matched - a.matched;
        if (b.score !== a.score) return b.score - a.score;
        return a.page.title.localeCompare(b.page.title);
      });

    if (matches.length <= TAIL_MIN_RESULTS) return matches;
    var floor = matches[0].score * TAIL_SCORE_RATIO;
    return matches.filter(function (match, i) {
      return i < TAIL_MIN_RESULTS || match.score >= floor;
    });
  }

  function occurrences(haystack, needle) {
    var count = 0;
    var at = haystack.indexOf(needle);
    while (at !== -1) {
      count++;
      at = haystack.indexOf(needle, at + needle.length);
    }
    return count;
  }

  function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  // Matches a term at a word start and runs to the end of that word, so a
  // partial query highlights the whole word it matched.
  function highlightPattern(terms) {
    var alternatives = terms.map(escapeRegExp).join('|');
    return new RegExp('\\b(?:' + alternatives + ')[\\w’\']*', 'gi');
  }

  function highlightInto(node, text, pattern) {
    pattern.lastIndex = 0;
    var last = 0;
    var match;
    while ((match = pattern.exec(text)) !== null) {
      if (match.index > last) node.appendChild(document.createTextNode(text.slice(last, match.index)));
      var mark = document.createElement('mark');
      mark.textContent = match[0];
      node.appendChild(mark);
      last = match.index + match[0].length;
      if (match[0].length === 0) pattern.lastIndex++; // guard against a zero-width match looping
    }
    if (last < text.length) node.appendChild(document.createTextNode(text.slice(last)));
  }

  // A window of body text around the first match. Falls back to the meta
  // description for pages that matched only on their title or URL.
  function snippet(page, terms) {
    var text = page.text || '';
    if (!text) return page.description || '';

    var pattern = highlightPattern(terms);
    var match = pattern.exec(text);
    if (!match) return page.description || truncate(text, SNIPPET_CHARS);

    var start = Math.max(0, match.index - SNIPPET_LEAD);
    if (start > 0) {
      var space = text.indexOf(' ', start);
      if (space !== -1 && space - start < 20) start = space + 1;
    }

    var excerpt = text.slice(start, start + SNIPPET_CHARS);
    if (start + SNIPPET_CHARS < text.length) excerpt = excerpt.replace(/\s+\S*$/, '') + '…';
    return (start > 0 ? '…' : '') + excerpt.trim();
  }

  function truncate(text, limit) {
    if (text.length <= limit) return text;
    return text.slice(0, limit).replace(/\s+\S*$/, '') + '…';
  }

  function prettyUrl(url) {
    var path = url.replace(/index\.html$/, '').replace(/\.html$/, '');
    return location.host + (path === '/' ? '' : path);
  }
})();
