#!/usr/bin/env node
/*
 * Stages the deployable site into dist/.
 *
 * The Webflow export lands in the repo root, alongside everything the repo
 * carries for its own sake - the Worker, the form handler, this script, the
 * docs. Cloudflare uploads an asset directory wholesale, so the two have to be
 * separated before deploying. dist/ is that separation: it holds the site and
 * nothing else.
 *
 * Pointing Cloudflare at the repo root instead was tried and rejected. Beyond
 * needing an ignore list that silently ships anything it forgets, wrangler
 * watches its asset directory during `wrangler dev` - and its own .wrangler/
 * state lives in the root, so every request reloaded the server in a loop.
 *
 * Run after a Webflow re-export, before deploying:
 *
 *   node tools/build-site.mjs
 *
 * No dependencies, and dist/ is gitignored - it is a build artefact, rebuilt
 * from the repo on every deploy.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');

/*
 * Top-level entries that are not the site.
 *
 * An exclude list rather than an include list on purpose: a re-export that adds
 * a new page or folder should ship without anyone remembering to list it, and
 * the failure mode of forgetting to exclude something is caught by the DENIED
 * list in worker/index.js, which refuses these paths a second time.
 */
const EXCLUDE = new Set([
  '.git',
  '.github',
  '.gitignore',
  '.assetsignore',
  '.wrangler',
  '.vscode',
  '.idea',
  'node_modules',
  'dist',
  'worker',
  'api',
  'tools',
  'docs',
  'README.md',
  'package.json',
  'package-lock.json',
  'wrangler.jsonc',
  'wrangler.toml',
  '_external',
  // Left over from the Railway deploy; excluded so it cannot be served even
  // while it is still in the repo.
  'Caddyfile',
  'Staticfile',
]);

/** Anything matching these is skipped at any depth. */
const EXCLUDE_ANYWHERE = [/^\.dev\.vars/, /^\.DS_Store$/, /^Thumbs\.db$/, /^node_modules$/];

function excluded(name, depth) {
  if (EXCLUDE_ANYWHERE.some((pattern) => pattern.test(name))) return true;
  return depth === 0 && EXCLUDE.has(name);
}

function copyDir(from, to, depth) {
  fs.mkdirSync(to, { recursive: true });

  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    if (excluded(entry.name, depth)) continue;

    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);

    if (entry.isDirectory()) copyDir(src, dest, depth + 1);
    else if (entry.isFile()) fs.copyFileSync(src, dest);
    // Symlinks and device files are not something a Webflow export produces;
    // skipping them keeps anything odd out of the upload.
  }
}

function countFiles(dir) {
  let files = 0;
  let bytes = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const nested = countFiles(full);
      files += nested.files;
      bytes += nested.bytes;
    } else {
      files += 1;
      bytes += fs.statSync(full).size;
    }
  }
  return { files, bytes };
}

/*
 * Empty dist/ by deleting its children rather than the directory itself.
 *
 * `wrangler dev` watches the asset directory and holds a handle on it, so
 * removing the directory fails with EPERM on Windows while a dev server is
 * running - which is exactly when someone is most likely to rebuild.
 */
function emptyDir(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir)) {
    fs.rmSync(path.join(dir, entry), {
      recursive: true,
      force: true,
      maxRetries: 5,
      retryDelay: 100,
    });
  }
}

emptyDir(DIST);
copyDir(ROOT, DIST, 0);

const { files, bytes } = countFiles(DIST);
console.log(`dist/  ${files} files, ${(bytes / 1024 / 1024).toFixed(1)} MB`);

// The site search fetches this at runtime; without it every query returns
// nothing, and it is generated by a separate script that is easy to forget.
if (!fs.existsSync(path.join(DIST, 'search-index.json'))) {
  console.warn('WARNING: search-index.json is missing - run: node tools/build-search-index.js');
}
